### ISSUE TITLE
Support for mph and miles (either through pre-set default or changeable field)

### ISSUE THREAD

**Issue by vovan-** [vovan-/cyclist-datafiled-garmin#5]

**Comment by vovan-** [comment]
Implemented. Watch configuration based.

**Comment by xemoterp** [comment]
Using my Fenix 3 w/6.25Beta firmware- latest cyclistdatafield version still only show km/h and km even though miles and mph units are selected in system settings.

**Comment by xemoterp** [comment]
Meant 6.15Beta ...

**Comment by vovan-** [comment]
Fixed potential problems with km/mi units.
Version 1.1.1.
Now speed and distance units settings may be configured separately.

**Comment by vovan-** [comment]
Setting applied only before starting activity. During activity settings won't apply.
